### ISSUE TITLE
切换到QQ音乐音源后点歌报错

### ISSUE THREAD

**Issue by VsentCN** [SilveryStar/Adachi-Plugin#2]
### 环境
- 系统：Windows Server 2019 DataCenter 64bitCN
- node 版本：13.13.0
- bot 版本：2.1.13

### 操作复述

切换到QQ音乐音源后点歌报错
### 配置文件

未修改
### 错误报告

(node:2460) UnhandledPromiseRejectionWarning: FetchError: request to https://api.qq.jsososo.com/search/quick?key=unravel failed, reason: connect ECONNREFUSED 47.111.244.251:443
    at ClientRequest.<anonymous> (C:\bot\node_modules\node-fetch\lib\index.js:1461:11)
    at ClientRequest.emit (events.js:315:20)
    at ClientRequest.EventEmitter.emit (domain.js:485:12)
    at TLSSocket.socketErrorListener (_http_client.js:432:9)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket.EventEmitter.emit (domain.js:485:12)
    at emitErrorNT (internal/streams/destroy.js:84:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:2460) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

**Comment by SilveryStar** [comment]
这应该是 api 的问题，跟我这边没关系，直接访问 `https://api.qq.jsososo.com/` 也是无法连接，毕竟是第三方的，如果过一段时间还是没法用的话再考虑换吧

**Comment by CMHopeSunshine** [comment]
QQ点歌还是不能用诶，大大能换一下吗

> 这应该是 api 的问题，跟我这边没关系，直接访问 `https://api.qq.jsososo.com/` 也是无法连接，毕竟是第三方的，如果过一段时间还是没法用的话再考虑换吧

**Comment by SilveryStar** [comment]
> QQ点歌还是不能用诶，大大能换一下吗

我尽快修复
